apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ql5jmm2n9-nodejs 
  janus-idp.io/tekton: ql5jmm2n9-nodejs
  backstage.io/kubernetes-id: ql5jmm2n9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ql5jmm2n9-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml