apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ql5jmm2n9-nodejs-gitops
  description: This is GitOps manifest for ql5jmm2n9-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ql5jmm2n9-nodejs
    backstage.io/kubernetes-id: ql5jmm2n9-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ql5jmm2n9-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ql5jmm2n9-nodejs
