apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ql5jmm2n9-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ql5jmm2n9-nodejs 
  name: ql5jmm2n9-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ql5jmm2n9-nodejs
    weight: 100 
